amqp-embedded/pom.xml
bom/pom.xml
core/pom.xml
examples/core/pom.xml
examples/pom.xml
examples/spring/pom.xml
kafka-avro-embedded/pom.xml
kafka-avro/pom.xml
kafka-embedded/pom.xml
kafka/pom.xml
micrometer/pom.xml
parent/pom.xml
pom.xml
rabbitmq/pom.xml
spring/pom.xml
util/pom.xml
zookeeper-embedded/pom.xml

[maven-release-plugin] prepare release atleon-0.0.9

---

kafka-avro-embedded/pom.xml
kafka-avro-embedded/src/main/java/io/atleon/kafka/avro/embedded/EmbeddedSchemaRegistry.java
kafka-avro/pom.xml
kafka-avro/src/main/java/io/atleon/kafka/avro/AvroSerDe.java
kafka-avro/src/main/java/io/atleon/kafka/avro/LoadingAvroDeserializer.java
kafka-avro/src/main/java/io/atleon/kafka/avro/LoadingAvroSerializer.java
kafka-avro/src/test/java/io/atleon/kafka/avro/TestReflectDecoderAvroDeserializer.java
kafka-avro/src/test/java/io/atleon/kafka/avro/TestReflectEncoderAvroSerializer.java
kafka-embedded/pom.xml
kafka-embedded/src/main/java/io/atleon/kafka/embedded/EmbeddedKafka.java
kafka-embedded/src/main/java/io/atleon/kafka/embedded/EmbeddedKafkaConfig.java
parent/pom.xml
rabbitmq/src/main/java/io/atleon/rabbitmq/AloConnectionFactory.java
zookeeper-embedded/pom.xml

Upgrade to latest Reactor library versions; Resolve resulting dependency issues
#14

#14: Upgrade to latest Reactor libraries

---

examples/spring/pom.xml
examples/spring/src/main/resources/application.properties
parent/pom.xml
spring/pom.xml
spring/src/main/java/io/atleon/spring/AloStreamApplicationListener.java
spring/src/main/java/io/atleon/spring/AloStreamStatusDto.java
spring/src/main/java/io/atleon/spring/AloStreamStatusService.java
spring/src/main/java/io/atleon/spring/AtleonManagementAutoConfiguration.java
spring/src/main/java/io/atleon/spring/AtleonManagementController.java
spring/src/main/java/io/atleon/spring/ConfiguredAloStream.java
spring/src/main/java/io/atleon/spring/ConfiguredAloStreamStatusService.java
spring/src/main/java/io/atleon/spring/Contexts.java
spring/src/main/resources/META-INF/spring.factories

- Add ConfiguredStream abstraction for bound Stream and Configuration
- Enable ConfiguredStreams to be started, stopped, and monitored
- Add REST controller that can be optionally enabled in order to access Streams
- Make auto start of Streams in Spring apps configurable

#23: Enable management of registered/configured Streams

---

core/src/main/java/io/atleon/core/AloStreamConfig.java
core/src/main/java/io/atleon/core/AloStreamNaming.java
core/src/test/java/io/atleon/core/AloStreamNamingTest.java

Implement a default naming strategy for StreamConfigs

#26 Implement a default naming strategy for AloStreamConfigs

---

core/src/main/java/io/atleon/core/AloFlux.java
core/src/test/java/io/atleon/core/AloFluxTest.java

#31: Implement `AloFlux::mapNotNull` and `AloFlux::mapPresent`

---

CHANGELOG.md
README.md
amqp-embedded/pom.xml
bom/pom.xml
core/pom.xml
examples/core/pom.xml
examples/pom.xml
examples/spring/pom.xml
kafka-avro-embedded/pom.xml
kafka-avro/pom.xml
kafka-embedded/pom.xml
kafka/pom.xml
micrometer/pom.xml
parent/pom.xml
polling/pom.xml
pom.xml
rabbitmq/pom.xml
spring/pom.xml
util/pom.xml
zookeeper-embedded/pom.xml

0.6.0: Update Changelog

---

aws-sns/pom.xml
aws-sns/src/main/java/io/atleon/aws/sns/AbstractSnsMessage.java
aws-sns/src/main/java/io/atleon/aws/sns/AloSnsSender.java
aws-sns/src/main/java/io/atleon/aws/sns/BodySerializer.java
aws-sns/src/main/java/io/atleon/aws/sns/ComposedSnsMessage.java
aws-sns/src/main/java/io/atleon/aws/sns/DefaultAloSnsSenderResultSubscriber.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsAddress.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsConfig.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsConfigSource.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsMessage.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsMessageCreator.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsSender.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsSenderMessage.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsSenderOptions.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsSenderResult.java
aws-sns/src/main/java/io/atleon/aws/sns/StringBodySerializer.java
aws-sns/src/test/java/io/atleon/aws/sns/AloSnsSenderTest.java
aws-sns/src/test/java/io/atleon/aws/sns/LocalStackDependentTest.java
aws-sns/src/test/java/io/atleon/aws/sns/SnsSenderTest.java
aws-testcontainers/src/main/java/io/atleon/aws/testcontainers/AtleonLocalStackContainer.java
bom/pom.xml
parent/pom.xml
pom.xml

#44: Implement AWS SNS sending

---

aws-sns/pom.xml
aws-sns/src/main/java/io/atleon/aws/sns/AloSnsSender.java
aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsSender.java
core/src/main/java/io/atleon/core/AloFlux.java
examples/spring/src/main/java/io/atleon/examples/spring/kafka/stream/KafkaGeneration.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/stream/RabbitMQGeneration.java
kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
kafka/src/test/java/io/atleon/kafka/TestKafkaConfigSourceFactory.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java
util/src/main/java/io/atleon/util/ConfigLoading.java

- Add hooks to AloFlux to allow Sender closing on termination
#48

#48: Implement Closeable on all Sender implementations

---

aws-sns/src/main/java/io/atleon/aws/sns/AloSnsSender.java
aws-sns/src/main/java/io/atleon/aws/sns/SnsSender.java
aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsSender.java
aws-sqs/src/main/java/io/atleon/aws/sqs/SqsSender.java
kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQMessage.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQMessageCreator.java

- Neglecting AloSnsSender and AloSqsSender for now until they get more usage

#61: Add missing Javadoc for Receiver and Sender implementations

---

aws-sqs/src/main/java/io/atleon/aws/sqs/SqsReceiver.java

Just implement `Subscription` in `SqsReceiver::Poller`
#70

#70: Have `SqsReceiver::Poller` simply implement `Subscription`

---

core/src/main/java/io/atleon/core/AloFlux.java
core/src/main/java/io/atleon/core/RateLimitingConfig.java
core/src/main/java/io/atleon/core/RateLimitingTransformer.java
core/src/test/java/io/atleon/core/RateLimitingTransformerTest.java

#81: Isolate blocking rate limit on its own Scheduler

---

aws-sns/src/main/java/io/atleon/aws/sns/AloSnsSender.java
aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsSender.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/stream/SqsProcessing.java
kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
parent/pom.xml
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQMessageSendInterceptor.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQSendInterceptor.java

- QoL refactoring
- Clean up Javadoc linking
- Remove unnecessary argument from RabbitMQMessageSendInterceptor
#79

#79: Refactor `AloKafkaSender` for consistency

---

kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
kafka/src/main/java/io/atleon/kafka/KafkaSendInterceptor.java

This will allow populating context on ProducerRecords
#78

#78: Add ability to intercept sent Kafka Records

---

kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
kafka/src/main/java/io/atleon/kafka/KafkaSendInterceptor.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQSendInterceptor.java

#87: Remove SendInterceptors

---

core/src/main/java/io/atleon/core/AcknowledgingPublisher.java
core/src/main/java/io/atleon/core/Contextual.java
kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
kafka/src/main/java/io/atleon/kafka/ContextualProducer.java
kafka/src/main/java/io/atleon/kafka/ContextualProducerFactory.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java

#89: Add missing contextual invocation of third party libs

---

aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
aws-sqs/src/main/java/io/atleon/aws/sqs/SqsConfig.java
core/src/main/java/io/atleon/core/AloDecoratorConfig.java
core/src/main/java/io/atleon/core/AloFactoryConfig.java
core/src/test/java/io/atleon/core/AloDecoratorConfigTest.java
kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
polling/src/main/java/io/atleon/polling/AloPollingReceiver.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQConfig.java

Centralize code for loading AloFactories for Alo*Receivers
#107

#107: Centralize code for loading AloFactories for Alo*Receivers

---

core/src/main/java/io/atleon/core/AloFlux.java
core/src/main/java/io/atleon/core/DeduplicatingTransformer.java
core/src/main/java/io/atleon/core/RateLimitingConfig.java
core/src/test/java/io/atleon/core/DeduplicatingTransformerTest.java
core/src/test/java/io/atleon/core/RateLimitingTransformerTest.java
examples/core/pom.xml
examples/core/src/main/java/io/atleon/examples/errorhandling/KafkaErrorHandling.java
examples/core/src/main/java/io/atleon/examples/parallelism/KafkaArbitraryParallelism.java
examples/core/src/main/java/io/atleon/examples/parallelism/KafkaTopicPartitionParallelism.java
util/src/main/java/io/atleon/util/FieldResolution.java
util/src/main/java/io/atleon/util/Throwing.java

#117: Remove unnecessary use of custom Schedulers

---

core/pom.xml
core/src/main/java/io/atleon/core/AloStream.java
parent/pom.xml

Make it more pleasant to use Atleon in Kotlin
#110

#110: Add NonNull annotations to `AloStream`

---

aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
aws-sqs/src/main/java/io/atleon/aws/sqs/DeserializedSqsMessage.java
aws-sqs/src/main/java/io/atleon/aws/sqs/ReceivedSqsMessage.java
aws-sqs/src/main/java/io/atleon/aws/sqs/SqsReceiver.java
aws-sqs/src/main/java/io/atleon/aws/sqs/SqsReceiverMessage.java
opentracing/src/main/java/io/atleon/opentracing/TracingAloReceivedRabbitMQMessageDecorator.java
opentracing/src/main/java/io/atleon/opentracing/TracingAloReceivedSqsMessageDecorator.java
rabbitmq/src/main/java/io/atleon/rabbitmq/ReceivedRabbitMQMessage.java

Add `queueUrl` accessor to `ReceivedSqsMessage`
#122

#122: Add `queueUrl` for received SQS Messages

---

core/src/main/java/io/atleon/core/AloFlux.java
core/src/test/java/io/atleon/core/DeduplicatingTransformerTest.java
examples/core/pom.xml
examples/core/src/main/java/io/atleon/examples/metrics/KafkaMicrometer.java
examples/core/src/main/java/io/atleon/examples/tracing/KafkaOpentracing.java
micrometer-auto/pom.xml
micrometer-auto/src/main/resources/META-INF/services/io.atleon.aws.sqs.AloReceivedSqsMessageDecorator
micrometer-auto/src/main/resources/META-INF/services/io.atleon.kafka.AloKafkaConsumerRecordDecorator
micrometer-auto/src/main/resources/META-INF/services/io.atleon.rabbitmq.AloReceivedRabbitMQMessageDecorator
micrometer/pom.xml
micrometer/src/main/java/io/atleon/micrometer/MeterFacade.java
micrometer/src/main/java/io/atleon/micrometer/MeteringAlo.java
micrometer/src/main/java/io/atleon/micrometer/MeteringAloDecorator.java
micrometer/src/main/java/io/atleon/micrometer/MeteringAloKafkaConsumerRecordDecorator.java
micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedRabbitMQMessageDecorator.java
micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedSqsMessageDecorator.java
opentracing/src/main/java/io/atleon/opentracing/TracerFacade.java
opentracing/src/main/java/io/atleon/opentracing/TracingAloKafkaConsumerRecordDecorator.java
parent/pom.xml
pom.xml

Record `Alo` starts and processing durations
#124

#124: Implement Micrometer `Alo` (Auto-)Decoration

---

micrometer/src/main/java/io/atleon/micrometer/AbstractKafkaMetricsReporter.java

#131: Deprecate `BLACKLIST` and `WHITELIST` in favor of `BLOCKLIST` and `ALLOWLIST`

---

aws-sqs/src/main/java/io/atleon/aws/sqs/AloReceivedSqsMessageDecorator.java
aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
aws-sqs/src/main/java/io/atleon/aws/sqs/DeserializedSqsMessage.java
aws-sqs/src/main/java/io/atleon/aws/sqs/ReceivedSqsMessage.java
aws-sqs/src/main/java/io/atleon/aws/sqs/SqsConfig.java
aws-sqs/src/main/java/io/atleon/aws/sqs/SqsReceiver.java
aws-sqs/src/main/java/io/atleon/aws/sqs/SqsReceiverMessage.java
core/src/main/java/io/atleon/core/AloDecoratorConfig.java
core/src/main/java/io/atleon/core/OrderManagingAcknowledgementOperator.java
kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedRabbitMQMessageDecorator.java
micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedSqsMessageDecorator.java
opentracing/src/main/java/io/atleon/opentracing/TracingAloReceivedRabbitMQMessageDecorator.java
opentracing/src/main/java/io/atleon/opentracing/TracingAloReceivedSqsMessageDecorator.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloReceivedRabbitMQMessageDecorator.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQConfig.java
rabbitmq/src/main/java/io/atleon/rabbitmq/ReceivedRabbitMQMessage.java

#134: Move decorator parameters to configuration arguments

---

core/src/main/java/io/atleon/core/AloDecoratorConfig.java
core/src/main/java/io/atleon/core/AloSignalObserverConfig.java
util/src/main/java/io/atleon/util/ConfigLoading.java
util/src/test/java/io/atleon/util/ConfigLoadingTest.java

#143: Do not load a `noOp` decoration when there are no auto decorators

---

spring/src/main/java/io/atleon/spring/AloStreamAutoConfiguration.java

#149: Ensure extraction of raw config type in auto configuration

---

kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
kafka/src/main/java/io/atleon/kafka/NacknowledgerFactory.java
rabbitmq/src/main/java/io/atleon/rabbitmq/NacknowledgerFactory.java

#156: Allow nacknowledger configuration in `AloKafkaReceiver`

---

aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
core/src/main/java/io/atleon/core/ErrorEmitter.java
kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQConfig.java

#167: Make best effort to ensure successful receiver error emission

---

core/src/main/java/io/atleon/core/AcknowledgingCollection.java
core/src/main/java/io/atleon/core/AcknowledgingPublisher.java
core/src/main/java/io/atleon/core/AloFailureStrategy.java
core/src/main/java/io/atleon/core/AloOps.java
core/src/test/java/io/atleon/core/AloFluxTest.java

#180: Enforce `AloFailureStrategy` when publishing

---

aws-sns/src/main/java/io/atleon/aws/sns/SnsConfig.java
bom/pom.xml
core/src/main/java/io/atleon/core/AloStreamConfig.java
kafka/src/main/java/io/atleon/kafka/KafkaSenderResult.java
kotlin/pom.xml
kotlin/src/main/kotlin/io/atleon/kotlin/AloFlux.kt
kotlin/src/test/kotlin/io/atleon/kotlin/AloFluxTest.kt
parent/pom.xml
pom.xml
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQSenderResult.java

- Provide Kotlin extension function on `AloFlux` for coroutines and Flow
#183

#183: Add Kotlin module

---

CHANGELOG.md
amqp-embedded/pom.xml
aws-sns/pom.xml
aws-sqs/pom.xml
aws-testcontainers/pom.xml
aws-util/pom.xml
bom/pom.xml
core/pom.xml
examples/core/pom.xml
examples/pom.xml
examples/spring/pom.xml
kafka-avro-embedded/pom.xml
kafka-avro/pom.xml
kafka-embedded/pom.xml
kafka/pom.xml
kotlin/pom.xml
micrometer-auto/pom.xml
micrometer/pom.xml
opentracing-auto/pom.xml
opentracing/pom.xml
parent/pom.xml
polling/pom.xml
pom.xml
rabbitmq/pom.xml
spring/pom.xml
util/pom.xml
zookeeper-embedded/pom.xml

0.16.0: Update Changelog

---

kafka-avro-embedded/pom.xml
kafka-avro/pom.xml
kafka-avro/src/main/java/io/atleon/kafka/avro/LoadingAvroDeserializer.java
kafka-avro/src/main/java/io/atleon/kafka/avro/LoadingAvroSerializer.java
parent/pom.xml

#189: Removed dependency on kafka-avro-serializer

---

aws/aws-sns/src/main/java/io/atleon/aws/sns/BodySerializer.java
aws/aws-sns/src/main/java/io/atleon/aws/sns/StringBodySerializer.java
aws/aws-sqs/src/main/java/io/atleon/aws/sqs/BodyDeserializer.java
aws/aws-sqs/src/main/java/io/atleon/aws/sqs/BodySerializer.java
aws/aws-sqs/src/main/java/io/atleon/aws/sqs/StringBodyDeserializer.java
aws/aws-sqs/src/main/java/io/atleon/aws/sqs/StringBodySerializer.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/stream/SqsProcessingConfig.java
rabbitmq/src/main/java/io/atleon/rabbitmq/BodyDeserializer.java
rabbitmq/src/main/java/io/atleon/rabbitmq/BodySerializer.java
rabbitmq/src/main/java/io/atleon/rabbitmq/ByteArrayBodyDeserializer.java
rabbitmq/src/main/java/io/atleon/rabbitmq/ByteArrayBodySerializer.java
rabbitmq/src/main/java/io/atleon/rabbitmq/LongBodyDeserializer.java
rabbitmq/src/main/java/io/atleon/rabbitmq/LongBodySerializer.java
rabbitmq/src/main/java/io/atleon/rabbitmq/StringBodyDeserializer.java
rabbitmq/src/main/java/io/atleon/rabbitmq/StringBodySerializer.java
schemas/kafka-avro/src/main/java/io/atleon/kafka/avro/LoadingAvroDeserializer.java
schemas/schema-registry-confluent/pom.xml
schemas/schema-registry-confluent/src/main/java/io/atleon/schemaregistry/confluent/AvroRegistryRabbitMQBodyDeserializer.java
schemas/schema-registry-confluent/src/main/java/io/atleon/schemaregistry/confluent/AvroRegistryRabbitMQBodySerializer.java

#192: Add RabbitMQ SerDe's for Avro

---

bom/pom.xml
parent/pom.xml
schemas/avro/src/main/java/io/atleon/avro/AvroDeserialization.java
schemas/avro/src/main/java/io/atleon/avro/AvroDeserializer.java
schemas/json-jackson/pom.xml
schemas/json-jackson/src/main/java/io/atleon/json/jackson/JsonKafkaSerializer.java
schemas/json-jackson/src/main/java/io/atleon/json/jackson/JsonNodeKafkaDeserializer.java
schemas/json-jackson/src/main/java/io/atleon/json/jackson/JsonNodeRabbitMQBodyDeserializer.java
schemas/json-jackson/src/main/java/io/atleon/json/jackson/JsonNodeSqsBodyDeserializer.java
schemas/json-jackson/src/main/java/io/atleon/json/jackson/JsonRabbitMQBodySerializer.java
schemas/json-jackson/src/main/java/io/atleon/json/jackson/JsonSnsBodySerializer.java
schemas/json-jackson/src/main/java/io/atleon/json/jackson/JsonSqsBodySerializer.java
schemas/json-jackson/src/main/java/io/atleon/json/jackson/ObjectMapperFacade.java
schemas/pom.xml
schemas/protobuf/pom.xml
schemas/protobuf/src/main/java/io/atleon/protobuf/ProtobufKafkaDeserializer.java
schemas/protobuf/src/main/java/io/atleon/protobuf/ProtobufKafkaSerializer.java
schemas/protobuf/src/main/java/io/atleon/protobuf/ProtobufMessages.java
schemas/protobuf/src/main/java/io/atleon/protobuf/ProtobufRabbitMQBodyDeserializer.java
schemas/protobuf/src/main/java/io/atleon/protobuf/ProtobufRabbitMQBodySerializer.java
schemas/protobuf/src/test/java/io/atleon/protobuf/ProtobufMessagesTest.java
util/src/main/java/io/atleon/util/ConfigLoading.java
util/src/test/java/io/atleon/util/ConfigLoadingTest.java

#195: First class support for Protobuf and JSON

---

core/src/main/java/io/atleon/core/AloQueueListener.java
core/src/main/java/io/atleon/core/AloQueueListenerConfig.java
core/src/main/java/io/atleon/core/AloQueueingOperator.java
core/src/main/java/io/atleon/core/AloQueueingTransformer.java
kafka/src/main/java/io/atleon/kafka/AloKafkaQueueListener.java
kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
observability/micrometer-auto/src/main/resources/META-INF/services/io.atleon.kafka.AloKafkaQueueListener
observability/micrometer/pom.xml
observability/micrometer/src/main/java/io/atleon/micrometer/AbstractKafkaMetricsReporter.java
observability/micrometer/src/main/java/io/atleon/micrometer/MeteringAloKafkaQueueListener.java
observability/micrometer/src/main/java/io/atleon/micrometer/MeteringAloQueueListener.java

#191: Enable export of metrics on `Alo` queuing

---

schemas/avro/src/test/java/io/atleon/avro/AvroSerDeTest.java
schemas/avro/src/test/java/io/atleon/avro/ReflectAvroSerDeTest.java
schemas/avro/src/test/java/io/atleon/avro/StringDataHolder.java
util/src/main/java/io/atleon/util/TypeResolution.java

#214: Avro SerDes identify classes with generic supertypes

---

schemas/avro/src/main/java/io/atleon/avro/AvroDeserializer.java
schemas/avro/src/main/java/io/atleon/avro/AvroSerializer.java
schemas/avro/src/test/java/io/atleon/avro/AvroUpgradeTest.java
schemas/schema-registry-confluent/src/main/java/io/atleon/schemaregistry/confluent/AvroRegistryDeserializer.java
schemas/schema-registry-confluent/src/main/java/io/atleon/schemaregistry/confluent/AvroRegistryDeserializerConfig.java

#218: Use default reader schema loading based on `GenericData` type

---

core/pom.xml
core/src/main/java/io/atleon/core/AcknowledgementQueue.java
core/src/main/java/io/atleon/core/AcknowledgementQueueMode.java
core/src/main/java/io/atleon/core/AloQueueingTransformer.java
core/src/test/java/io/atleon/core/AcknowledgementQueueTest.java
core/src/test/java/io/atleon/core/AloQueueingTransformerPerformanceTest.java

Implement acknowledgement compaction, and allow optional usage
#202

#202: Implement compact acknowledgement queueing

---

kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
kafka/src/main/java/io/atleon/kafka/KafkaConfig.java

#223: Enable configuration of AloKafkaReceiver's AcknowledgementQueue mode

---

aws/aws-sns/src/main/java/io/atleon/aws/sns/SnsConfigSource.java
aws/aws-sqs/src/main/java/io/atleon/aws/sqs/SqsConfigSource.java
core/src/main/java/io/atleon/core/ConfigSource.java
kafka/src/main/java/io/atleon/kafka/KafkaConfigSource.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQConfigSource.java

#245: Add `KafkaConfigSource.unnamed()`

---

core/src/main/java/io/atleon/core/ResubscribingTransformer.java

Upgrade error logging level in `ResubscribingTransformer`
#249

[#249] Log stream errors at ERROR level

---

examples/spring/src/test/java/io/atleon/examples/spring/rabbitmq/IntegrationTest.java
observability/opentracing/src/main/java/io/atleon/opentracing/TracingAloReceivedRabbitMQMessageDecorator.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AbstractRabbitMQMessageCreator.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQMessage.java
rabbitmq/src/main/java/io/atleon/rabbitmq/ReceivedRabbitMQMessage.java

[#252] Improve parity between RMQ message APIs and others

---

kotlin/src/main/kotlin/io/atleon/kotlin/AloFlux.kt
kotlin/src/main/kotlin/io/atleon/kotlin/GroupFlux.kt

[#254] Fix nullity of Kotlin suspend extension functions

---

core/src/main/java/io/atleon/core/AloFlux.java
core/src/main/java/io/atleon/core/GroupFlux.java
kotlin/src/main/kotlin/io/atleon/kotlin/AloFlux.kt
kotlin/src/main/kotlin/io/atleon/kotlin/GroupFlux.kt
parent/pom.xml

- Bump to latest Reactor version
- Allow setting `fairBackpressure` on `bufferTimeout`
#257

#257: Allow configuration of prefetch on `suspendMap`

---

core/src/main/java/io/atleon/core/AloStreamNaming.java
core/src/test/java/io/atleon/core/AloStreamNamingTest.java

[#260] Fix special cases when converting names to kebab-case

---

core/src/main/java/io/atleon/core/AbstractDelegatingAlo.java
core/src/main/java/io/atleon/core/AloErrorDelegatingMapper.java
core/src/main/java/io/atleon/core/AloFlux.java
observability/opentracing/src/main/java/io/atleon/opentracing/TracingAlo.java
observability/opentracing/src/test/java/io/atleon/opentracing/TracingAloTest.java

- Reduce code duplication on delegation
- Fix delegator naming
#271

[#271] Ensure contextual invocations on TracingAlo are forwarded

---

aws/aws-sqs/src/main/java/io/atleon/aws/sqs/ContextActivatingAloReceivedSqsMessageDecorator.java
bom/pom.xml
context-auto/pom.xml
context-auto/src/main/resources/META-INF/services/io.atleon.aws.sqs.AloReceivedSqsMessageDecorator
context-auto/src/main/resources/META-INF/services/io.atleon.kafka.AloKafkaConsumerRecordDecorator
context-auto/src/main/resources/META-INF/services/io.atleon.rabbitmq.AloReceivedRabbitMQMessageDecorator
core/src/main/java/io/atleon/context/AloContext.java
core/src/main/java/io/atleon/context/ContextActivatingAlo.java
core/src/main/java/io/atleon/context/ContextActivatingAloDecorator.java
core/src/test/java/io/atleon/context/AloContextTest.java
core/src/test/java/io/atleon/context/ContextActivatingAloTest.java
kafka/src/main/java/io/atleon/kafka/ContextActivatingAloKafkaConsumerRecordDecorator.java
pom.xml
rabbitmq/src/main/java/io/atleon/rabbitmq/ContextActivatingAloReceivedRabbitMQMessageDecorator.java

[#273] Implement Alo context propagation and management

---

aws/aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
aws/aws-sqs/src/main/java/io/atleon/aws/sqs/NacknowledgerFactory.java
core/src/main/java/io/atleon/core/ErrorDelegator.java
core/src/test/java/io/atleon/core/ErrorDelegatorTest.java
examples/core/src/main/java/io/atleon/examples/deadlettering/KafkaDeadlettering.java

[#279] Add simple Error Delegation API

---

core/src/main/java/io/atleon/context/ContextActivatingAloDecorator.java
core/src/main/java/io/atleon/core/AloDecorator.java
core/src/test/java/io/atleon/core/AloDecoratorTest.java
observability/micrometer/src/main/java/io/atleon/micrometer/MeteringAloDecorator.java
observability/opentracing/src/main/java/io/atleon/opentracing/TracingAloConsumptionDecorator.java

Implement ordering for `AloDecorator`
#282

[#282] Make `AloDecorator` application deterministic

---

kafka/src/main/java/io/atleon/kafka/KafkaConfigSource.java

[#289] Fix generic parameter types on KafkaConfigSource

---

kafka/src/main/java/io/atleon/kafka/KafkaConfig.java
util/src/main/java/io/atleon/util/ConfigLoading.java
util/src/test/java/io/atleon/util/ConfigLoadingTest.java

[#292] Enable loading "native" properties from `KafkaConfig`

---

core/src/main/java/io/atleon/core/AloFlux.java
core/src/main/java/io/atleon/core/GroupFlux.java

[#299] Implement `GroupFlux::limitPerSecond`

---

README.md
core/src/main/java/io/atleon/core/DefaultAloSenderResultSubscriber.java

[#304] Negative ack on DefaultAloSenderResultSubscriber should log at ERROR

---

core/src/main/java/io/atleon/core/StarterStopper.java
core/src/main/java/io/atleon/core/StarterStopperConfig.java
kafka/src/main/java/io/atleon/kafka/KafkaLagThresholdStarterStopper.java
kafka/src/test/java/io/atleon/kafka/KafkaLagThresholdStarterStopperTest.java
spring/pom.xml
spring/src/main/java/io/atleon/application/AbstractConfiguredAloStream.java
spring/src/main/java/io/atleon/spring/AloStreamApplicationListener.java

[#306] Dynamic start-stop including Kafka lag-based impl

---

core/pom.xml
core/src/main/java/io/atleon/core/CompositeAloStream.java
core/src/test/java/io/atleon/core/CompositeAloStreamTest.java
parent/pom.xml
spring/src/main/java/io/atleon/spring/AloStreamAutoConfiguration.java
spring/src/main/java/io/atleon/spring/AutoConfigureStream.java
spring/src/main/java/io/atleon/spring/Contexts.java

[#308] Allow configuring multiple copied instances of `AloStream`

---

examples/spring/pom.xml
parent/pom.xml
spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports

[#313] Enable compatibility with Spring Boot 3.x+

---

examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/config/AwsConfiguration.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/stream/SnsGenerationStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/stream/SqsConsumptionStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/stream/SqsProcessingStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/kafka/config/KafkaConfiguration.java
examples/spring/src/main/java/io/atleon/examples/spring/kafka/stream/KafkaConsumptionStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/kafka/stream/KafkaGenerationStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/kafka/stream/KafkaProcessingStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/config/RabbitMQConfiguration.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/stream/RabbitMQConsumptionStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/stream/RabbitMQGenerationStream.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/stream/RabbitMQGenerationStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/stream/RabbitMQProcessingStreamConfig.java
spring/src/main/java/io/atleon/spring/SpringAloStreamConfig.java

- Update examples to use simplified conventions
#315

[#315] Implement `SpringAloStreamConfig`

---

examples/spring/pom.xml
parent/pom.xml
schemas/schema-registry-confluent-embedded/pom.xml

- kafka-clients: 3.4.1 -> 3.6.1
- confluent: 7.4.2 -> 7.6.1
- kotlinx-coroutines: 1.6.4 -> 1.8.0
- reactor-kafka: 1.3.21 -> 1.3.23
#317

[#317] Version refresh

---

kafka/src/main/java/io/atleon/kafka/KafkaConfig.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQConfig.java
util/src/main/java/io/atleon/util/ConfigLoading.java

[#322] Enable instance loading from Configs

---

core/src/main/java/io/atleon/core/ConfigContext.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/config/SnsConfiguration.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/config/SnsToSqsInitializer.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/config/SqsConfiguration.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/stream/SnsGenerationStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/stream/SqsConsumptionStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/awssnssqs/stream/SqsProcessingStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/kafka/stream/KafkaConsumptionStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/kafka/stream/KafkaGenerationStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/kafka/stream/KafkaProcessingStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/config/RabbitMQConfiguration.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/stream/RabbitMQConsumptionStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/stream/RabbitMQGenerationStreamConfig.java
examples/spring/src/main/java/io/atleon/examples/spring/rabbitmq/stream/RabbitMQProcessingStreamConfig.java
spring/src/main/java/io/atleon/spring/AtleonConfigContextAutoConfiguration.java
spring/src/main/java/io/atleon/spring/SpringConfigContext.java

[#325] Refactor `ConfigContext` to be a "core" concept

---

core/src/main/java/io/atleon/core/AloStream.java
core/src/main/java/io/atleon/core/SelfConfigurableAloStream.java
examples/spring/pom.xml
parent/pom.xml
spring/pom.xml
spring/src/main/java/io/atleon/spring/AtleonConfigSourcesAutoConfiguration.java
spring/src/main/java/io/atleon/spring/ConfigSourcesRegistrar.java
spring/src/main/resources/META-INF/spring.factories
spring/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
spring/src/test/java/io/atleon/spring/ConfigSourcesRegistrarTest.java
spring/src/test/resources/application-config-sources.properties

[#329] Implement dynamic ConfigSource registration for Spring

---

aws/aws-sns/src/main/java/io/atleon/aws/sns/SnsConfig.java
aws/aws-sqs/src/main/java/io/atleon/aws/sqs/SqsConfig.java
core/src/main/java/io/atleon/core/CompositeAloStream.java
core/src/main/java/io/atleon/core/PropertiesFileConfigProcessor.java
core/src/test/java/io/atleon/core/PropertiesFileConfigProcessorTest.java
kafka/src/main/java/io/atleon/kafka/KafkaConfig.java
rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQConfig.java

[#330] Implement config source processing from `properties` files

---

spring/src/main/java/io/atleon/spring/AloStreamAutoConfiguration.java
spring/src/main/java/io/atleon/spring/AutoConfigureStream.java
spring/src/main/java/io/atleon/spring/Contexts.java

[#335] Enable instance count configuration by expression

---

kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
kafka/src/main/java/io/atleon/kafka/ProhibitableConsumerFactory.java

[#334] Manually prohibit further consumer interactions beyond close deadline

---

core/src/main/java/io/atleon/core/AloFlux.java
core/src/main/java/io/atleon/core/ErrorEmitter.java
core/src/test/java/io/atleon/context/ContextActivatingAloTest.java
core/src/test/java/io/atleon/core/AloFluxTest.java
kafka/src/main/java/io/atleon/kafka/KafkaBoundedReceiver.java
kafka/src/main/java/io/atleon/kafka/OffsetRangeProvider.java
kafka/src/main/java/io/atleon/kafka/ReactiveAdmin.java
kotlin/src/test/kotlin/io/atleon/kotlin/AloFluxTest.kt
observability/opentracing/src/test/java/io/atleon/opentracing/TracingAloTest.java

- Use new convenience method in the many appropriate places
- Clean up some formatting
#343

[#343] Add `AloFlux.just` convenience method

---

amqp-embedded/pom.xml
amqp-embedded/src/main/java/io/atleon/amqp/embedded/EmbeddedAmqp.java
parent/pom.xml
zookeeper-embedded/pom.xml

[#349] Bump versions of QPID, Curator, and ZooKeeper

---

kafka/src/main/java/io/atleon/kafka/OffsetCriteria.java
kafka/src/main/java/io/atleon/kafka/RecordRange.java
kafka/src/test/java/io/atleon/kafka/KafkaBoundedReceiverTest.java

[#347] Allow specifying consumer group as `OffsetCriteria`

---

kafka/src/main/java/io/atleon/kafka/MachineData.java
kafka/src/main/java/io/atleon/kafka/SingleMachinePartitionAssignor.java
kafka/src/test/java/io/atleon/kafka/MachineDataTest.java
kafka/src/test/java/io/atleon/kafka/SingleMachinePartitionAssignorTest.java

[#357] Implement `SingleMachinePartitionAssignor`

---

core/src/main/java/io/atleon/core/AloStreamConfig.java
core/src/main/java/io/atleon/core/Autostart.java
spring/src/main/java/io/atleon/application/AbstractConfiguredAloStream.java
spring/src/main/java/io/atleon/spring/SpringAloStream.java
spring/src/test/java/io/atleon/application/AbstractConfiguredAloStreamTest.java

[#374] Enable configuring autostart enablement

---

core/src/main/java/io/atleon/core/StreamPropertyResolver.java
spring/src/main/java/io/atleon/spring/SpringAloStream.java
spring/src/test/java/io/atleon/spring/SpringAloStreamTest.java

- Consolidate available methods
- Standardize on usage of `Optional` methods for fallback values
#370

[#370] Rework contract for stream property resolution

---

aws/aws-util/pom.xml
parent/pom.xml

Add `software.amazon.awssdk` to the class path so that it can work with web identity tokens
Closes #382

#382: Add the sts module to the class path

---

schemas/json-jackson/src/main/java/io/atleon/json/jackson/JsonKafkaSerializer.java
schemas/protobuf/src/main/java/io/atleon/protobuf/ProtobufKafkaSerializer.java

[#387] Correctly handle `null` in Kafka serializers

---

core/src/main/java/io/atleon/core/AloFlux.java
core/src/main/java/io/atleon/core/DeduplicatingTransformer.java
core/src/main/java/io/atleon/core/Deduplication.java
core/src/main/java/io/atleon/core/DeduplicationConfig.java
core/src/test/java/io/atleon/core/DeduplicatingTransformerTest.java
examples/core/src/main/java/io/atleon/examples/deduplication/KafkaDeduplication.java

[#389] Simplify and standardize deduplication APIs

---

core/src/main/java/io/atleon/core/AloFlux.java

[#392] Enable configuring `Scheduler` on `limitPerSecond`

---

parent/pom.xml

[#407] Downgrade Kafka from 3.9.1 to 3.7.1

---

infrastructures/kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
infrastructures/kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
infrastructures/kafka/src/main/java/io/atleon/kafka/ConsumptionSpec.java
infrastructures/kafka/src/main/java/io/atleon/kafka/KafkaReceiver.java
infrastructures/kafka/src/main/java/io/atleon/kafka/PollStrategyFactory.java
infrastructures/kafka/src/main/java/io/atleon/kafka/PollingSubscriptionFactory.java
infrastructures/kafka/src/main/java/io/atleon/kafka/ReceivingConsumer.java
infrastructures/kafka/src/test/java/io/atleon/kafka/ReceivingConsumerTest.java

- Enables support of Kafka 4.0 out of the box
#385

[#385] Default to "optimized" Kafka clients

---

infrastructures/zookeeper-embedded/pom.xml

[#352] Exclude transitive dependence on JUnit from Apache Curator

---

infrastructures/kafka/src/main/java/io/atleon/kafka/KafkaReceiverOptions.java
infrastructures/kafka/src/main/java/io/atleon/kafka/PollManager.java
infrastructures/kafka/src/main/java/io/atleon/kafka/PollingSubscriptionFactory.java
infrastructures/kafka/src/test/java/io/atleon/kafka/PollManagerTest.java

- Add log messages to commit-on-revocation code path
- Remove unnecessary recursive poll in PollManager
Should help with debugging bug from #439 if it recurs
#439

[#439] Increase logging insight into commit timing
