- kafka-avro/src/main/java/io/atleon/kafka/avro/LoadingAvroDeserializer.java
- kafka-avro/src/test/java/io/atleon/kafka/avro/LoadingAvroSerDeTest.java
- kafka-avro/src/test/java/io/atleon/kafka/avro/ReflectDecoderAvroSerDeTest.java
Detect and handle cases where Avro data has valid first byte but not enough bytes for Schema ID, and `read.null.on.failure` is enabled
#3
> [#3]Fix unhandled BufferUnderflowException in LoadingAvroDeserializer when `read.null.on.failure` is enabled

- kafka-avro-embedded/pom.xml
- kafka-embedded/src/main/java/io/atleon/kafka/embedded/EmbeddedKafka.java
- parent/pom.xml
Upgrading to more recent versions of Kafka and Confluent
> Bump Kafka and Confluent to 2.8.1 and 6.2.2

- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQMessageFactory.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/BodyDeserializer.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/BodySerializer.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/Configurable.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQConfig.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQMessageSendInterceptor.java
- util/src/main/java/io/atleon/util/ConfigLoading.java
- util/src/main/java/io/atleon/util/Configurable.java
Standardize on usage of `io.atleon.util.Configurable` and move its functionalit to `util`
#45
> #45: Move `Configurable` to `util` module

- aws-sns/src/main/java/io/atleon/aws/sns/SnsSender.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/SqsMessageVisibilityChanger.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/SqsReceiver.java
- core/src/main/java/io/atleon/core/DrainableQueue.java
- core/src/test/java/io/atleon/core/DrainableQueueTest.java
Use Reactor's drain-miss pattern to implement a work-stealing queue for serializing emissions. Apply to SQS message deletion
#57
> #57: Make SQS Message deletion non-blocking

- aws-sns/src/main/java/io/atleon/aws/sns/SnsSender.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/SqsSender.java
- core/src/main/java/io/atleon/core/Batcher.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java
- Include a little bit of refactoring on SQS and SNS Senders
> #59: Add single-message send methods to Kafka and RabbitMQ Alo Senders

- README.md
- aws-sns/src/main/java/io/atleon/aws/sns/AloSnsSender.java
- aws-sns/src/main/java/io/atleon/aws/sns/DefaultAloSnsSenderResultSubscriber.java
- aws-sns/src/main/java/io/atleon/aws/sns/SnsSenderResult.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsSender.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/DefaultAloSqsSenderResultSubscriber.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/SqsSenderResult.java
- core/src/main/java/io/atleon/core/DefaultAloSenderResultSubscriber.java
- core/src/main/java/io/atleon/core/SenderResult.java
- examples/core/src/main/java/io/atleon/examples/errorhandling/KafkaErrorHandling.java
- kafka/src/main/java/io/atleon/kafka/DefaultAloKafkaSenderResultSubscriber.java
- kafka/src/main/java/io/atleon/kafka/KafkaSenderResult.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/DefaultAloRabbitMQSenderResultSubscriber.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQSenderResult.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/UnackedRabbitMQMessageException.java
All Sender Results now implement same base interface
#73
> #73: Implement base interface for all Sender Results

- core/src/main/java/io/atleon/core/AloExtendedFlux.java
- core/src/main/java/io/atleon/core/AloFlux.java
- core/src/main/java/io/atleon/core/GroupFlux.java
- examples/core/src/main/java/io/atleon/examples/errorhandling/KafkaErrorHandling.java
- examples/core/src/main/java/io/atleon/examples/parallelism/KafkaArbitraryParallelism.java
- examples/core/src/main/java/io/atleon/examples/parallelism/KafkaTopicPartitionParallelism.java
- parent/pom.xml
- pom.xml
- New `GroupFlux` is easier to use since concurrency does not need to be explicitly provided
- Take a pass at cleaning up Javadoc
#76
> #76: Replace and deprecate `AloExtendedFlux` with `GroupFlux`

- aws-sns/src/main/java/io/atleon/aws/sns/AloSnsSender.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsSender.java
- core/src/main/java/io/atleon/core/Alo.java
- core/src/main/java/io/atleon/core/Contextual.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java
- Will allow the activation context, i.e. for Tracing
In order to enable full APM tracing from sent items to downstream consumers, Alo items need a way to activate their tracing context when those natively sendable items are generated. This is typically done without going through `Alo.map`, so this adds a context-aware method to allow Alo items to activate their context on arbitrary invocations of methods that supply results
#78
> #78: Add Contextual interface and have Alo extend it

- aws-sns/src/main/java/io/atleon/aws/sns/AloSnsSender.java
- aws-sns/src/main/java/io/atleon/aws/sns/SnsSenderResult.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsSender.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/SqsSenderResult.java
- core/src/main/java/io/atleon/core/Alo.java
- core/src/main/java/io/atleon/core/AloFactory.java
- core/src/main/java/io/atleon/core/AloFlux.java
- core/src/main/java/io/atleon/core/AloOps.java
- core/src/main/java/io/atleon/core/AloQueueingSubscriber.java
- core/src/main/java/io/atleon/core/DeduplicatingTransformer.java
- core/src/main/java/io/atleon/core/Deduplication.java
`Alo` implementations will now have the ability to be aware of the fact that other `Alo`s are being "fanned in" vs. propagated to downstream results. This has resulted in several simplifications as well as future abilities:
1. Removed exposure of how to create Alo items from microbatches in `AloFlux`
2. No longer need to expose how to "invert" List of Alo to Alo of List. Relocated and simplified.
3. Future `Alo` implementations will be able to do interesting things, like link to multiple contexts, when data is fanned-in through operations like microbatching and deduplication
#91
> #91: Implement ability to differentiate fan-in from regular propagation

- bom/pom.xml
- core/src/main/java/io/atleon/core/AbstractDecoratingAlo.java
- core/src/test/java/io/atleon/core/AloDecoratorConfigTest.java
- core/src/test/java/io/atleon/core/TestAloDecorator.java
- core/src/test/resources/META-INF/services/io.atleon.core.AloDecorator
- examples/README.md
- examples/core/pom.xml
- examples/core/src/main/java/io/atleon/examples/metrics/KafkaMicrometer.java
- examples/core/src/main/java/io/atleon/examples/tracing/KafkaOpentracing.java
- examples/spring/pom.xml
- opentracing-auto/pom.xml
- opentracing-auto/src/main/resources/META-INF/services/io.atleon.aws.sqs.AloReceivedSqsMessageDecorator
- opentracing-auto/src/main/resources/META-INF/services/io.atleon.kafka.AloKafkaConsumerRecordDecorator
- opentracing-auto/src/main/resources/META-INF/services/io.atleon.rabbitmq.AloRabbitMQMessageDecorator
- opentracing/pom.xml
- opentracing/src/main/java/io/atleon/opentracing/ConsumerTracing.java
- opentracing/src/main/java/io/atleon/opentracing/TracerFacade.java
- opentracing/src/main/java/io/atleon/opentracing/TracingAlo.java
- opentracing/src/main/java/io/atleon/opentracing/TracingAloKafkaConsumerRecordDecorator.java
- opentracing/src/main/java/io/atleon/opentracing/TracingAloRabbitMQMessageDecorator.java
- opentracing/src/main/java/io/atleon/opentracing/TracingAloReceivedSqsMessageDecorator.java
- opentracing/src/test/java/io/atleon/opentracing/TestAlo.java
- opentracing/src/test/java/io/atleon/opentracing/TestTracer.java
- opentracing/src/test/java/io/atleon/opentracing/TracingAloTest.java
- parent/pom.xml
- pom.xml
- Add `AloDecorator`s for Opentracing on available Receviers
- Include auto-decoration functionality through `ServiceLoader`
#86
> #86: Add Opentracing integration

- aws-sns/src/main/java/io/atleon/aws/sns/AloSnsSender.java
- aws-sns/src/main/java/io/atleon/aws/sns/SnsConfig.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsSender.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/NacknowledgerFactory.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/SqsConfig.java
- aws-util/src/main/java/io/atleon/aws/util/AwsConfig.java
- core/src/main/java/io/atleon/core/AloDecorator.java
- core/src/main/java/io/atleon/core/AloDecoratorConfig.java
- core/src/main/java/io/atleon/core/ConfigSource.java
- core/src/test/java/io/atleon/core/AloDecoratorConfigTest.java
- kafka-avro/src/main/java/io/atleon/kafka/avro/AvroSchemas.java
- kafka-avro/src/main/java/io/atleon/kafka/avro/LoadingAvroDeserializer.java
- kafka-avro/src/main/java/io/atleon/kafka/avro/LoadingAvroSerializer.java
- kafka-avro/src/main/java/io/atleon/kafka/avro/ReflectDecoderAvroDeserializer.java
- kafka-avro/src/main/java/io/atleon/kafka/avro/ReflectEncoderAvroSerializer.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
- kafka/src/main/java/io/atleon/kafka/KafkaConfigSource.java
- micrometer/src/main/java/io/atleon/micrometer/AbstractKafkaMetricsReporter.java
- opentracing/src/main/java/io/atleon/opentracing/TracingAloKafkaConsumerRecordDecorator.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/RabbitMQConfig.java
- util/pom.xml
- util/src/main/java/io/atleon/util/ConfigLoading.java
- util/src/main/java/io/atleon/util/Instantiation.java
- util/src/main/java/io/atleon/util/TypeResolution.java
- util/src/test/java/io/atleon/util/ConfigLoadingTest.java
- Pass through loaded config values if they are already the correct type
- Make `ConfigLoading` responsible for all instantiation of config values
- Make `ConfigLoading` responsible for configuring `Configurable` objects
#109
> #109: Smarter Config Loading

- aws-sqs/src/main/java/io/atleon/aws/sqs/AloReceivedSqsMessageSignalListener.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
- core/src/main/java/io/atleon/core/AloFlux.java
- core/src/main/java/io/atleon/core/AloSignalListener.java
- core/src/main/java/io/atleon/core/AloSignalListenerConfig.java
- examples/README.md
- examples/core/src/main/java/io/atleon/examples/metrics/KafkaMicrometer.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaConsumerRecordSignalListener.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
- micrometer-auto/src/main/resources/META-INF/services/io.atleon.aws.sqs.AloReceivedSqsMessageSignalListener
- micrometer-auto/src/main/resources/META-INF/services/io.atleon.kafka.AloKafkaConsumerRecordSignalListener
- micrometer-auto/src/main/resources/META-INF/services/io.atleon.rabbitmq.AloReceivedRabbitMQSignalListener
- micrometer/pom.xml
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloKafkaConsumerRecordSignalListener.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedRabbitMQMessageSignalListener.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedSqsMessageSignalListener.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloSignalListener.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/AloReceivedRabbitMQMessageSignalListener.java
- Add `AloSignalListener` to be plugged in to reactive `Alo` pipelines
- Copy `auto` functionality from `AloDecorator`
- Implement Micrometer listeners and add to `auto` listeners files
- Deprecate AloFlux#metrics in favor of `doOnEach`
#136
> #136: Implement `Signal` listening on `Alo` pipelines

- core/src/main/java/io/atleon/core/AloFlux.java
- examples/core/src/main/java/io/atleon/examples/metrics/KafkaMicrometer.java
- micrometer/src/main/java/io/atleon/micrometer/MeterFacade.java
- micrometer/src/main/java/io/atleon/micrometer/MeterKey.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAlo.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloDecorator.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloKafkaConsumerRecordDecorator.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloKafkaConsumerRecordSignalListener.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedRabbitMQMessageDecorator.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedRabbitMQMessageSignalListener.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedSqsMessageDecorator.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloReceivedSqsMessageSignalListener.java
- micrometer/src/main/java/io/atleon/micrometer/MeteringAloSignalListener.java
For any given metric name, ensure same tags are always provided
#138
> #138: Make metric naming and tagging consistent

- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
> #158: Close RabbitMQ Receiver after every `AloFlux` termination

- core/src/main/java/io/atleon/core/AloFlux.java
- core/src/main/java/io/atleon/core/AloOps.java
- core/src/test/java/io/atleon/core/AloFluxTest.java
Allow more intuitive terminal consumption of data items and subsequent subscription
#154
> #154: Provide terminal `consume` operator on `AloFlux`

- core/src/main/java/io/atleon/core/AcknowledgementQueue.java
- core/src/main/java/io/atleon/core/AloOps.java
- core/src/main/java/io/atleon/core/MultipleAcknowledgementOperator.java
- core/src/main/java/io/atleon/core/MultipleAcknowledgementQueue.java
- core/src/main/java/io/atleon/core/OrderManagingAcknowledgementOperator.java
- core/src/main/java/io/atleon/core/OrderManagingAcknowledgementQueue.java
- core/src/test/java/io/atleon/core/AloQueuingSubscriberTest.java
- core/src/test/java/io/atleon/core/MultipleAcknowledgementQueueTest.java
- core/src/test/java/io/atleon/core/OrderManagingAcknowledgementQueueTest.java
- Always execute acknowledgement in order
- Rely on the fact that we can't drop `Alo` items
#162
> #162: Always execute acknowledgement in order

- aws-sns/src/main/java/io/atleon/aws/sns/AloSnsSender.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsSender.java
- core/src/main/java/io/atleon/core/AloFailureStrategy.java
- core/src/main/java/io/atleon/core/AloFlux.java
- core/src/main/java/io/atleon/core/AloGroupedFlux.java
- core/src/main/java/io/atleon/core/AloOps.java
- core/src/main/java/io/atleon/core/DefaultAloSenderResultSubscriber.java
- core/src/main/java/io/atleon/core/ErrorEmitter.java
- core/src/main/java/io/atleon/core/SenderResult.java
- core/src/test/java/io/atleon/core/AloFluxTest.java
- examples/core/src/main/java/io/atleon/examples/errorhandling/KafkaErrorHandling.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQSender.java
* Add methods similar to Reactor's `onError*` methods
* `onAloErrorEmit`: Treat all errors as terminal by emitting them into the pipeline (this is the default)
* `onAloErrorEmitUnless(Predicate)`: Treat all errors as terminal, unless the error matches the predicate, in which case, acknowledge and move on
* `onAloErrorDelegate`: Delegate failure handling to the pipeline, and either negatively acknowledge or forward the error as a data item in the pipeline
* `onAloErrorDelegate(Predicate)`: Delegate failure handling to pipeline, unless the error matches the predicate, in which case, acknowledge and move on
#169
> #169: Implement configurable and consistent `Alo` failure handling modes

- aws-sqs/src/main/java/io/atleon/aws/sqs/SqsMessageVisibilityChanger.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/SqsReceiver.java
- aws-sqs/src/main/java/io/atleon/aws/sqs/SqsReceiverMessage.java
Avoid unbounded memory usage by considering SQS messages still in flight until a successful response is received from SQS after having marked the messages as no longer in process.
#171
> #171: SQS messages still in flight until terminal response received

- aws-sqs/src/main/java/io/atleon/aws/sqs/AloSqsReceiver.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
- kafka/src/main/java/io/atleon/kafka/KafkaConfig.java
- kafka/src/main/java/io/atleon/kafka/KafkaConfigSource.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
- util/src/main/java/io/atleon/util/ConfigLoading.java
- Instead of producing `Map<String, Object>` from `KafkaConfigSource`, produce an encapsulation
- Stop passing around raw config in Kafka Receiver and Sender
#172
> #172: Encapsulate Kafka config as `KafkaConfig`

- core/src/main/java/io/atleon/core/AloFlux.java
- examples/core/src/main/java/io/atleon/examples/errorhandling/KafkaErrorHandling.java
- examples/core/src/main/java/io/atleon/examples/parallelism/KafkaTopicPartitionParallelism.java
> #177: Remove implicit `groupBy` methods on `AloFlux`

- kotlin/src/main/kotlin/io/atleon/kotlin/AloFlux.kt
- kotlin/src/test/kotlin/io/atleon/kotlin/AloFluxTest.kt
- Make `suspendMap` smart enough to detect mapping to `Unit` and use `publish` instead of `mono`
#186
> #186: Remove `suspendConsume` in favor of just `suspendMap`

- core/src/main/java/io/atleon/core/AloErrorDelegatingMapper.java
- core/src/main/java/io/atleon/core/AloFlux.java
- core/src/test/java/io/atleon/core/AloFluxTest.java
- examples/core/src/main/java/io/atleon/examples/deadlettering/KafkaDeadlettering.java
- examples/core/src/main/java/io/atleon/examples/deduplication/KafkaDeduplication.java
- examples/core/src/main/java/io/atleon/examples/endtoendtoend/KafkaPart1.java
- examples/core/src/main/java/io/atleon/examples/endtoendtoend/KafkaPart2.java
- examples/core/src/main/java/io/atleon/examples/endtoendtoend/KafkaPart3.java
- examples/core/src/main/java/io/atleon/examples/endtoendtoend/KafkaPart4.java
- examples/core/src/main/java/io/atleon/examples/errorhandling/KafkaErrorHandling.java
- examples/core/src/main/java/io/atleon/examples/infrastructuralinteroperability/KafkaToRabbitMQ.java
- examples/core/src/main/java/io/atleon/examples/metrics/KafkaMicrometer.java
- Implements fluent delegation of failures to reactive delegate
- Includes example usage applied to deadlettering
#204
> #204: Implement fluent `Alo` error delegation

- core/src/main/java/io/atleon/core/AcknowledgementQueue.java
Refactors `AcknolwedgementQueue` to take ownership of InFlight linked listing. This allows us to more easily implement acknowledgement compaction
#202
> #202: Extract In-Flight queueing to manual linked list

- core/src/main/java/io/atleon/core/AcknowledgingPublisher.java
- core/src/test/java/io/atleon/core/AloFluxTest.java
Guard against downstream cancellation after error emission in `AcknowledgingPublisher`
#226
> #226: Mark `AcknowledgingPublisher` inactive with error emission

- core/src/main/java/io/atleon/core/Acknowledgement.java
- core/src/main/java/io/atleon/core/AcknowledgementQueue.java
- rabbitmq/src/main/java/io/atleon/rabbitmq/AloRabbitMQReceiver.java
- Make sure acknowledgement on `Alo` produced by `AloRabbitMQReceiver` is idempotent
- Add `Acknowledgement`
- Minor code improvements to `AcknowledgementQueue`
#232
> #232: Ensure Alo produced by AloRabbitMQReceiver is idempotent

- core/src/main/java/io/atleon/core/ActivityEnforcingTransformer.java
> #236: Use `long` to represent last active epoch millisecond rather than `Instant`

- parent/pom.xml
- schemas/schema-registry-confluent-embedded/pom.xml
Updated to modern versions of:
- Reactor: 3.5.14
- Kafka: 3.4.1
- AWS SDK: 2.20.162
- AMQP Client: 5.18.0
- JUnit: 5.10.1
- Testcontainers: 1.19.3
#284
> [#284] Dependency version refresh - January '24

- kafka/pom.xml
- kafka/src/main/java/io/atleon/kafka/KafkaBoundedReceiver.java
- kafka/src/main/java/io/atleon/kafka/OffsetCriteria.java
- kafka/src/main/java/io/atleon/kafka/OffsetRange.java
- kafka/src/main/java/io/atleon/kafka/OffsetRangeProvider.java
- kafka/src/main/java/io/atleon/kafka/RawOffsetRange.java
- kafka/src/main/java/io/atleon/kafka/ReactiveAdmin.java
- kafka/src/main/java/io/atleon/kafka/TopicPartitionGroupOffsets.java
- kafka/src/test/java/io/atleon/kafka/KafkaBoundedReceiverTest.java
- kafka/src/test/java/io/atleon/kafka/ReactiveAdminTest.java
- kafka/src/test/java/org/apache/kafka/clients/admin/TestDescribeTopicsResult.java
- kafka/src/test/java/org/apache/kafka/clients/admin/TestListConsumerGroupOffsetsResult.java
- util/src/main/java/io/atleon/util/ConfigLoading.java
- util/src/test/java/io/atleon/util/ConfigLoadingTest.java
Initial implementation of reusable Kafka administration-oriented utilities.
[#302]
> [#302] Initial pass at Kafka utility functions

- core/src/main/java/io/atleon/core/ErrorEmitter.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaBoundedReceiver.java
- kafka/src/main/java/io/atleon/kafka/KafkaBoundedReceiver.java
- kafka/src/main/java/io/atleon/kafka/OffsetRangeProvider.java
- kafka/src/main/java/io/atleon/kafka/ReactiveAdmin.java
- kafka/src/main/java/io/atleon/kafka/RecordRange.java
- kafka/src/main/java/io/atleon/kafka/TopicPartitionGroupOffsets.java
- kafka/src/test/java/io/atleon/kafka/AloKafkaBoundedReceiverTest.java
- kafka/src/test/java/io/atleon/kafka/ReactiveAdminTest.java
> [#345] Enable `KafkaBoundedReceiver` to consume `Alo` records based on configured consumer group

- kafka/src/main/java/io/atleon/kafka/SingleMachinePartitionAssignor.java
- kafka/src/test/java/io/atleon/kafka/SingleMachinePartitionAssignorTest.java
Fix bug where empty member ID assignments were missing
#366
> [#366] Must return member ID assignment, even if empty

- kafka/src/main/java/io/atleon/kafka/KafkaLagThresholdStarterStopper.java
- kafka/src/test/java/io/atleon/kafka/KafkaLagThresholdStarterStopperTest.java
Extends KafkaLagThresholdStarterStopper to monitor total lag across multiple consumer groups.
* https://github.com/atleon/atleon/issues/372
> [#372] Monitor total lag across multiple consumer group ids

- aws/aws-util/src/main/java/io/atleon/aws/util/AwsConfig.java
Allow the `WebIdentityTokenFileCredentialsProvider` to be an explicit AWS credentials provider for Atleon, such as with Atleon SQS receiers
Resolves #379
> #379: Add explicit support for WebIdentityTokenFileCredentialsProvider

- kafka-embedded/pom.xml
- kafka/src/main/java/io/atleon/kafka/AloKafkaReceiver.java
- kafka/src/main/java/io/atleon/kafka/AloKafkaSender.java
- kafka/src/main/java/io/atleon/kafka/ConsumerMutexEnforcer.java
- kafka/src/main/java/io/atleon/kafka/ContextualProducer.java
- kafka/src/main/java/io/atleon/kafka/KafkaBoundedReceiver.java
- kafka/src/main/java/io/atleon/kafka/KafkaConfig.java
- kafka/src/main/java/io/atleon/kafka/KafkaSenderResult.java
- kafka/src/main/java/io/atleon/kafka/LegacyReceiveResources.java
- kafka/src/test/java/io/atleon/kafka/AloKafkaReceiverTest.java
- parent/pom.xml
Enable using new/optimized Kafka Receiver+Sender implementations by setting `kafka.receiver.reception.type`+`kafka.sender.sending.type` to `"OPTIMIZED"`
#396
> [#398] Enable migration to optimized Kafka Receiver+Sender

- kafka/src/main/java/io/atleon/kafka/AloKafkaBoundedReceiver.java
- kafka/src/main/java/io/atleon/kafka/KafkaComparators.java
- kafka/src/main/java/io/atleon/kafka/KafkaReceiver.java
- kafka/src/main/java/io/atleon/kafka/OffsetRangeProvider.java
- kafka/src/main/java/io/atleon/kafka/PollManager.java
- kafka/src/main/java/io/atleon/kafka/PollSelectionContext.java
- kafka/src/main/java/io/atleon/kafka/PollStrategy.java
- kafka/src/test/java/io/atleon/kafka/PollManagerTest.java
- kafka/src/test/java/io/atleon/kafka/PollStrategyTest.java
- util/src/main/java/io/atleon/util/Collecting.java
- util/src/test/java/io/atleon/util/CollectingTest.java
- Provide for ability to post-process polled records in poll strategies
- Extract a few reusable methods, including default topic-partition ordering and `takeUntil` on collections
#427
> [#427] Enable+implement strategic prioritized polling
